name       : haskell-OpenGLRaw
version    : 3.3.0.1
release    : 4
source     :
    - https://hackage.haskell.org/package/OpenGLRaw-3.3.0.1/OpenGLRaw-3.3.0.1.tar.gz : d889e4040791957157f001d0236c148f531a45007a2215b7e03adbad90baf14b
license    : BSD-3-Clause
component  : programming.haskell
summary    : OpenGLRaw is a raw Haskell binding for the OpenGL 4.5 graphics system and lots of OpenGL extensions.
description: |
    OpenGLRaw is a raw Haskell binding for the OpenGL 4.5 graphics system and lots of OpenGL extensions.
builddeps  :
    - pkgconfig(gl)
    - ghc
    - haskell-cabal-install
    - haskell-fixed
    - haskell-half
    - haskell-text
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
