name       : haskell-OpenGLRaw
version    : 3.2.2.0
release    : 1
source     :
    - http://hackage.haskell.org/package/OpenGLRaw-3.2.2.0/OpenGLRaw-3.2.2.0.tar.gz : 65df144730044166fd8ea2f81470d71e6c5026a7c31df6be45aac9e6ddf93771
license    : BSD-3-Clause
component  : programming
summary    : OpenGLRaw is a raw Haskell binding for the OpenGL 4.5 graphics system and lots of OpenGL extensions.
description: |
    OpenGLRaw is a raw Haskell binding for the OpenGL 4.5 graphics system and lots of OpenGL extensions.
builddeps  :
    - pkgconfig(gl)
    - ghc
    - haskell-fixed
    - haskell-half
    - haskell-text
setup      : |
    sudo ghc-pkg recache
    ghc -threaded Setup
    ./Setup configure --enable-shared \
                      --prefix=/usr \
                      --docdir="/usr/share/doc/\$compiler/\$pkgid" \
                      --libdir=/usr/lib64 \
                      --libsubdir="\$compiler/\$pkgid" \
                      --datadir=/usr/share \
                      --sysconfdir=/etc
build      : |
    ./Setup %JOBS% build
install    : |
    export GHCV=`readlink /usr/bin/ghc`
    ./Setup copy --destdir=$installdir
    ./Setup register --gen-pkg-config
    install -D -m 00644 OpenGLRaw-$version.conf $installdir/usr/lib64/$GHCV/package.conf.d/OpenGLRaw-$version.conf
