name       : haskell-OpenGLRaw
version    : 3.2.2.0
release    : 3
source     :
    - http://hackage.haskell.org/package/OpenGLRaw-3.2.2.0/OpenGLRaw-3.2.2.0.tar.gz : 65df144730044166fd8ea2f81470d71e6c5026a7c31df6be45aac9e6ddf93771
license    : BSD-3-Clause
component  : programming.haskell
summary    : OpenGLRaw is a raw Haskell binding for the OpenGL 4.5 graphics system
    and lots of OpenGL extensions.
description: |
    OpenGLRaw is a raw Haskell binding for the OpenGL 4.5 graphics system and lots of OpenGL extensions.
builddeps  :
    - pkgconfig(gl)
    - ghc
    - haskell-cabal-install
    - haskell-fixed
    - haskell-half
    - haskell-text
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
