name       : haskell-OpenGLRaw
version    : 3.3.4.0
release    : 6
source     :
    - https://hackage.haskell.org/package/OpenGLRaw-3.3.4.0/OpenGLRaw-3.3.4.0.tar.gz : 756169eaadfe16627a893c35e7952d82ff466ac77b13ec2d1ea1de8fb5afba3e
license    : BSD-3-Clause
component  : programming.haskell
summary    : OpenGLRaw is a raw Haskell binding for the OpenGL 4.5 graphics system and lots of OpenGL extensions.
description: |
    OpenGLRaw is a raw Haskell binding for the OpenGL 4.5 graphics system and lots of OpenGL extensions.
builddeps  :
    - pkgconfig(gl)
    - haskell-cabal-install
    - haskell-fixed-devel
    - haskell-half-devel
rundeps    :
    - devel:
        - haskell-fixed-devel
        - haskell-half-devel
        - libglvnd-devel
networking : yes
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
